# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10.15.2

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - publish

install:
  stage: build
  script:
    - npm --version
    - node --version
    - npm install

build_zip:
  stage: build
  script:
    - npm run build:pack
  artifacts:
    expire_in: '1 hour'
    paths:
      - web-ext-artifacts/d-chat-$CI_BUILD_TAG.zip
  only:
    - tags

publish:
  image: inetprocess/gitlab-release
  stage: publish
  script:
    - gitlab-release --message 'Extension zip:' web-ext-artifacts/d-chat-$CI_BUILD_TAG.zip
  only:
    - tags

pages:
  stage: publish
  script:
    - npm run build:web
    - rm -rf extension/lib/js/{webextensions-lib-configs,browser-polyfill.js}
    - mv extension/* public
  artifacts:
    paths:
      - public
  only:
    - master
